### ISSUE TITLE
Consider eliminating dependency on Flurl

### ISSUE THREAD

**Issue by goldsam** [silentpartnersoftware/Keycloak.Net#29]
Consider eliminating dependency on Flurl. Flurl is a lot of complexity and cruft that adds needless overhead.

**Comment by sps-campbellwray** [comment]
Hi @goldsam, this request not in scope for this project and would require a complete rewrite of the project, while also potentially causing issues for the existing users.

If you would like a Keycloak library for .NET that is written entirely using the native HttpClient you should consider forking this repository and releasing your own NuGet package.

Thanks for taking the time to open an issue.
