### ISSUE TITLE
[Advice] Targetting .NET 4.7

### ISSUE THREAD

**Issue by Webrow** [silentpartnersoftware/Keycloak.Net#36]
I was looking for out of the box ideas for using keycloak. 
Since we will integrate keycloak v20+ for another project I am currently in the exploration phase for integrating it.
Ive found solutions targetting .net 4.7, but for lower versions of KC, and targetting higher versions of KC for .net 6.0
Assuming upgrading to 6.0 is not a viable option right now, I would be looking at making this repo compatible with 4.7. 
I am asking the maintainer if this is a "no go" for syntastic reasons, dependencies. Or do you have pointers as to what and how.
Else I'll try to implement it file by file. 

Kind regards,

**Comment by sps-campbellwray** [comment]
Hi @Webrow 

I don't really have any suggestions for targeting .NET 4.7 with this project, but you might have some luck with the (now abandoned) project that this project forked from https://github.com/silentpartnersoftware/Keycloak.Net/commit/65378cc8911b7f4c256eb6236db6ed599ef63d9b. It should run on .NET 4.7 the main issue is that the endpoint definitions in that project might be outdated, however depending on the features you need to use it might just work.

If it doesn't, I believe that the primary commit that was made to add support for Keycloak 17+ was this one https://github.com/silentpartnersoftware/Keycloak.Net/commit/65378cc8911b7f4c256eb6236db6ed599ef63d9b, so you might get away with adding that single change to that old project and it might be enough to get it working.

You can [compare the changes](https://github.com/lvermeulen/Keycloak.Net/compare/main...silentpartnersoftware:Keycloak.Net:main) that were made to this project, while there are a lot, they're not complicated, so if there is an endpoint that isn't working then you might be able to port the few changes you need for your use case.

I've never worked with the original repo, but if there is anything that I can do to help please let me know.

Campbell

**Comment by Webrow** [comment]
Thanks Campbell,

Ill try and pick it up this way. We can close this ticket, or keep it open for correspondation, but I can imagine you want your  tracker to be empty. I see you added Flurl in there at some point, was this necessary, or does it just make things easier? 

Web

**Comment by sps-campbellwray** [comment]
@Webrow 

I don't recall whether it is possible to reply to closed tickets, but if not then feel free to open another one, or start a discussion in the Discussions tab.

As for Flurl, I believe it was always in the project, and the change you are seeing is possibly just when it was upgraded to the latest version. I think you'll be fine with whatever version is present in that project.

Campbell
