### ISSUE TITLE
PartialImport not working anymore

### ISSUE THREAD

**Issue by bwagner-phoenis** [silentpartnersoftware/Keycloak.Net#53]
When unsing the PartialImport function a HTTP Error 500 is returned.
We see this behaviour after we updated to the latest versions with System.Text.Json serialization.
With the old versions everything works fine.

The only difference in the request content JSON we could find is that the policy is all uppercase in the old version and in the version only the first letter is written in uppercase. For example "SKIP" is now "Skip".

In the [PartialImport.cs](src/Keycloak.Net.Core/Models/RealmsAdmin/PartialImport.cs) file the Converter for the Policy Attribute has changed. In the earlier Versions a custom PolicyConverter was used and now the Default Enum Serializer is used.

We suspect that this causes the issue in keycloak to return the 500 Error Message

**Comment by sps-campbellwray** [comment]
Hi @bwagner-phoenis, sorry for the slow response, I have been on vacation for a few weeks and have some things to catch up on. I have asked @psavva to take a look at your issue, as he was asking about how he could contribute to the repo. 

If you don't hear back about a release to fix your issue soon then feel free to tag me and I'll do my best to get your issue resolved.

Have a good day!

**Comment by sps-campbellwray** [comment]
@bwagner-phoenis Apologies for the delay, I have opened a PR, could you please test that it works, and if so I will merge it. 

- Campbell
