### ISSUE TITLE
Kudos for maintaining this library

### ISSUE THREAD

**Issue by psavva** [silentpartnersoftware/Keycloak.Net#54]
I just wanted to say Kudos to you for maintaining this library.
Need any help? I will contribute too

**Comment by sps-campbellwray** [comment]
Thanks @psavva! Fortunately maintaining this library (at least to the extent I do) isn't too difficult, it's mostly a matter of reviewing PRs from other members of the community, such as yourself. 

I personally only use a small subset of this library, so I often don't notice when things aren't working, unless someone opens an issue, and then I do my best to investigate and solve it.

If you would like to contribute feel free to take a look at the open issues, some should be quite easy to resolve, such as #53, others require more work and might need some discussion as to how to best resolve the issue (as they are more than just mapping an API call with Flurl).

If you decide to take on any issues, just leave a comment, so I know not to work on them simultaneously 😄

**Comment by psavva** [comment]
💯
