### ISSUE TITLE
Support of "Organizations" feature

### ISSUE THREAD

**Issue by e-lippmann** [silentpartnersoftware/Keycloak.Net#55]
Organizations have been introduced with Keycloak 26 and are part of the Admin REST API (https://www.keycloak.org/docs-api/latest/rest-api/index.html#OrganizationRepresentation).

Are there any plans to support this feature?

**Comment by sps-campbellwray** [comment]
Hi @e-lippmann,

I took a look and there appears to be about 18 new endpoints that were added for the organizations feature. I can probably get these new endpoints added, but I might need some help with testing that it all works as I am not very familiar with the feature. 

Is that something you would be able to help with?

Thanks,
Campbell

**Comment by e-lippmann** [comment]
Hi Campbell,
I'm currently developing an app that uses the organizations feature. So I'm happy to help with testing.

**Comment by sps-campbellwray** [comment]
@e-lippmann I have opened a PR adding the new endpoints.

The API documentation for the organizations endpoints wasn't perfect but I think I have got it now. 

One thing that I wasn't sure about is that there are two endpoints listed for "Returns the organizations associated with the user that has the specified id". They have slightly different paths, so I'm not sure which one is correct, for now I have added the first one.

Please let me know once you have tested out the branch and I'll get it merged.

Campbell
